federation_version: =2.7.0
subgraphs:
  monolith:
    routing_url: http://localhost:4001
    schema:
      file: ./monolith/schema.graphql
  accounts:
    routing_url: http://localhost:4002
    schema:
      file: ./subgraph-accounts/schema.graphql
